#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { escapeHTML, hash, readBook, readFigure, renderDocument, validateBook } from './book-lib.mjs';

const scriptsDir = path.dirname(fileURLToPath(import.meta.url));

export function buildHTML(book) {
  const { config, documents } = book;
  const style = fs.readFileSync(path.join(scriptsDir, 'reader.css'), 'utf8');
  const script = fs.readFileSync(path.join(scriptsDir, 'reader.js'), 'utf8');
  const tooling = Object.fromEntries(['book-lib.mjs', 'build-reader.mjs', 'vendor/marked-17.0.5.mjs'].map(file => [file, hash(fs.readFileSync(path.join(scriptsDir, file)))]));
  const figures = documents.flatMap(document => document.images.map(href => [href, readFigure(href, document).sha256]));
  const sourceDigest = hash(JSON.stringify({ config, figures, sources: documents.map(document => [path.basename(document.file), document.markdown]), style, script, tooling }));
  const digest64 = content => crypto.createHash('sha256').update(content).digest('base64');
  const csp = `default-src 'none'; script-src 'sha256-${digest64(script)}'; style-src 'sha256-${digest64(style)}'; img-src data:; base-uri 'none'; form-action 'none'`;
  const data = JSON.stringify({ id: config.id, title: config.title, documents: documents.map(document => ({ id: document.id, title: document.title, text: document.searchText })) }).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
  const navigation = config.groups.map(group => `<section class="nav-group"><h2>${escapeHTML(group.title)}</h2><ul>${documents.filter(document => document.group === group.title).map(document => `<li><a class="nav-link" data-document="${escapeHTML(document.id)}" href="#${escapeHTML(document.id)}">${escapeHTML(document.title)}</a></li>`).join('')}</ul></section>`).join('\n');
  const content = documents.map(document => `<article class="chapter" id="${escapeHTML(document.id)}" aria-label="${escapeHTML(document.title)}">${renderDocument(document, documents)}</article>`).join('\n');
  return `<!doctype html>
<!-- Generated by scripts/build-reader.mjs. Do not edit this file directly. -->
<!-- Source SHA-256: ${sourceDigest} -->
<html lang="zh-TW">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="${escapeHTML(csp)}">
<meta name="description" content="${escapeHTML(config.subtitle)}">
<meta name="color-scheme" content="light">
<title>${escapeHTML(config.title)}</title>
<style>${style}</style>
</head>
<body>
<a class="skip-link" href="#main-content">跳至正文</a>
<header class="topbar">
  <button id="menu-toggle" class="mobile-only" type="button" aria-controls="book-navigation" aria-expanded="false">目錄</button>
  <a class="brand" href="#${escapeHTML(documents[0].id)}">${escapeHTML(config.title)}</a>
  <span class="progress-label" id="progress-label">本篇 0%</span>
  <progress id="reading-progress" value="0" max="100" aria-label="本篇閱讀進度"></progress>
</header>
<div class="shell">
  <aside class="sidebar" id="book-navigation" aria-label="目錄與搜尋">
    <label class="search-label" for="book-search">搜尋全書</label>
    <input class="search" id="book-search" type="search" placeholder="輸入概念、人物或關鍵字" autocomplete="off" spellcheck="false">
    <p class="search-hint">按 / 開始搜尋；按 Esc 清除搜尋或收起目錄。</p>
    <p class="search-status" id="search-status" role="status" aria-live="polite"></p>
    <nav aria-label="篇章">${navigation}</nav>
    <div class="sidebar-footer"><p>${escapeHTML(config.footer)}</p><p>閱讀進度會儲存在這個瀏覽器。全書可離線閱讀；來源連結須連上網路。</p><button id="print-book" type="button">列印全書</button></div>
  </aside>
  <main id="main-content" tabindex="-1">
    <p class="book-subtitle">${escapeHTML(config.subtitle)}</p>
    <noscript><p class="no-script">JavaScript 未啟用，目前顯示全書。您仍可使用目錄與瀏覽器的尋找功能閱讀。</p></noscript>
    ${content}
    <nav class="pager" aria-label="前後篇章"><a id="previous-chapter" hidden></a><a id="next-chapter" hidden></a></nav>
  </main>
</div>
<script id="book-data" type="application/json">${data}</script>
<script>${script}</script>
</body>
</html>
`;
}

function main() {
  const args = process.argv.slice(2);
  if (args.includes('--help')) {
    console.log('Usage: node scripts/build-reader.mjs [--check] [--config path]\nBuilds a deterministic single-file offline reader after structural validation. --check compares existing output without writing.');
    return;
  }
  const configIndex = args.indexOf('--config');
  const configFile = configIndex >= 0 ? args[configIndex + 1] : path.join(scriptsDir, '../web/book.config.json');
  const book = readBook(configFile);
  const report = validateBook(book);
  if (!report.pass) throw new Error(`Book validation failed:\n${report.errors.join('\n')}`);
  const html = buildHTML(book);
  const output = path.resolve(book.configDir, book.config.output);
  if (args.includes('--check')) {
    if (!fs.existsSync(output) || fs.readFileSync(output, 'utf8') !== html) throw new Error('Reader output is missing or stale. Run build-reader.mjs to regenerate it.');
    console.log(`PASS: Reader matches source bytes (${Buffer.byteLength(html)} bytes; SHA-256 ${hash(html)}).`);
  } else {
    const temporary = `${output}.tmp`;
    fs.writeFileSync(temporary, html, 'utf8');
    fs.renameSync(temporary, output);
    console.log(`Built ${path.relative(book.bookRoot, output)} (${Buffer.byteLength(html)} bytes; SHA-256 ${hash(html)}).`);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { main(); } catch (error) { console.error(error.message); process.exitCode = 1; }
}
